version: "3"
services:
  db:
    image: postgres:10.7
    restart: always
    env_file: .env.local
    volumes:
      - ./logs:/var/log/postgresql
    command: >
      postgres -c logging_collector=on
              -c log_statement=all
              -c log_directory=/var/log/postgresql
              -c log_filename=postgresql-%Y-%m-%d.log
    ports:
      - "5439:5432"
